### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by heckmic** [fungus75/ioBroker.zoe2#30]
The Adapter is not working anymore:

`
<html>
<body>

TypeError: Cannot read property 'cookieValue' of undefined at Request._callback (/opt/iobroker/node_modules/iobroker.zoe2/main.js:225:40) at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22) at Request.emit (events.js:375:28) at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1154:10) at Request.emit (events.js:375:28) at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1076:12) at Object.onceWrapper (events.js:481:28) at IncomingMessage.emit (events.js:387:35) at endReadableNT (internal/streams/readable.js:1317:12) at processTicksAndRejections (internal/process/task_queues.js:82:21)
--

</body>
</html>`

**Comment by heckmic** [comment]
Reenter Password...
