### ISSUE TITLE
Version 0.2.4 crashed

### ISSUE THREAD

**Issue by NoRitz952** [fungus75/ioBroker.zoe2#39]
Nach dem Update von 0.2.3 auf 0.2.4 kann ich keine Daten mehr auslesen. 
Die Version crashed:
2022-02-22 11:10:04.074	error	instance system.adapter.zoe2.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
zoe2.0
2022-02-22 11:10:03.501	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason
zoe2.0
2022-02-22 11:10:03.490	error	Cannot read property 'cookieValue' of undefined
zoe2.0
2022-02-22 11:10:03.489	error	TypeError: Cannot read property 'cookieValue' of undefined at /opt/iobroker/node_modules/iobroker.zoe2/main.js:245:40 at processTicksAndRejections (internal/process/task_queues.js:97:5)
zoe2.0
2022-02-22 11:10:03.487	error	unhandled promise rejection: Cannot read property 'cookieValue' of undefined
zoe2.0
2022-02-22 11:10:03.486	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

PLATTFORM: LINUX
BETRIEBSSYSTEM: LINUX
ARCHITEKTUR: ARM
CPUS: 4
MODELL: ARMV7 PROCESSOR REV 4 (V7L)
RAM: 926 MB
NODE.JS: V12.18.0
NPM: 6.14.13

**Comment by fungus75** [comment]
Kannst du bitte im Betriebssystem (über Putty oder ähnliches) einsteigen und folgenden Befehl absetzen: 

iobroker debug zoe2

Der sollte etwas mehr schreiben als der Auszug aus dem Logfile.

**Comment by NoRitz952** [comment]
pi@ioBroker-RasPi:~ $ iobroker debug zoe2
Debugger listening on ws://127.0.0.1:9229/d18069e2-8983-46f3-9fe5-61c97a854e61
For help, see: https://nodejs.org/en/docs/inspector
2022-02-22 11:37:11.465  - debug: zoe2.0 (30540) Redis Objects: Use Redis connection: 127.0.0.1:9001
2022-02-22 11:37:11.565  - debug: zoe2.0 (30540) Objects client ready ... initialize now
2022-02-22 11:37:11.575  - debug: zoe2.0 (30540) Objects create System PubSub Client
2022-02-22 11:37:11.579  - debug: zoe2.0 (30540) Objects create User PubSub Client
2022-02-22 11:37:11.583  - debug: zoe2.0 (30540) Objects client initialize lua scripts
2022-02-22 11:37:11.612  - debug: zoe2.0 (30540) Objects connected to redis: 127.0.0.1:9001
2022-02-22 11:37:11.630  - debug: zoe2.0 (30540) objectDB connected
2022-02-22 11:37:11.636  - debug: zoe2.0 (30540) Redis States: Use Redis connection: 127.0.0.1:6379
2022-02-22 11:37:11.651  - debug: zoe2.0 (30540) States create System PubSub Client
2022-02-22 11:37:11.654  - debug: zoe2.0 (30540) States create User PubSub Client
2022-02-22 11:37:11.669  - debug: zoe2.0 (30540) States connected to redis: 127.0.0.1:6379
2022-02-22 11:37:11.671  - debug: zoe2.0 (30540) statesDB connected
2022-02-22 11:37:12.043  - info: zoe2.0 (30540) starting. Version 0.2.4 in /opt/iobroker/node_modules/iobroker.zoe2, node: v12.18.0, js-controller: 3.3.22
2022-02-22 11:37:12.136  - debug: zoe2.0 (30540) in: processNextStep, curStep: 0
2022-02-22 11:37:12.139  - debug: zoe2.0 (30540) in:  globalInit v0.02
2022-02-22 11:37:12.141  - info: zoe2.0 (30540) Username:nritz@web.de
2022-02-22 11:37:12.143  - info: zoe2.0 (30540) Locale:de_DE
2022-02-22 11:37:12.144  - info: zoe2.0 (30540) VIN:VF1AGVYC058718566
2022-02-22 11:37:12.145  - info: zoe2.0 (30540) Country:DE
2022-02-22 11:37:12.147  - info: zoe2.0 (30540) ignoreApiError:true
2022-02-22 11:37:12.151  - info: zoe2.0 (30540) URL: https://renault-wrd-prod-1-euw1-myrapp-one.s3-eu-west-1.amazonaws.com/configuration/android/config_de_DE.json
2022-02-22 11:37:12.210  - debug: zoe2.0 (30540) out: globalInit
2022-02-22 11:37:12.449  - debug: zoe2.0 (30540) Data received from Renault server
2022-02-22 11:37:12.451  - info: zoe2.0 (30540) gigyarooturl:https://accounts.eu1.gigya.com
2022-02-22 11:37:12.452  - info: zoe2.0 (30540) gigyaapikey:3_7PLksOyBRkHv126x5WhHb-5pqC1qFR8pQjxSeLB6nhAnPERTUlwnYoznHSxwX668
2022-02-22 11:37:12.453  - info: zoe2.0 (30540) kamereonrooturl:https://api-wired-prod-1-euw1.wrd-aws.com
2022-02-22 11:37:12.455  - info: zoe2.0 (30540) kamereonapikey:Ae9FDWugRxZQAGm3Sxgk7uJn6Q4CGEA2
2022-02-22 11:37:12.459  - debug: zoe2.0 (30540) in: processNextStep, curStep: 1
2022-02-22 11:37:12.461  - debug: zoe2.0 (30540) in:  loginToGigya v0.02
2022-02-22 11:37:12.771  - debug: zoe2.0 (30540) Data received from gigyarooturl server
2022-02-22 11:37:12.772  - info: zoe2.0 (30540) FullBody:{"callId":"0485247ba05f4de0b05c93eafd519bef","errorCode":403042,"errorDetails":"invalid loginID or password","errorMessage":"Invalid LoginID","apiVersion":2,"statusCode":403,"statusReason":"Forbidden","time":"2022-02-22T10:37:12.738Z"}
2022-02-22 11:37:12.774  - info: zoe2.0 (30540) sessionInfo:undefined
2022-02-22 11:37:12.777  - error: zoe2.0 (30540) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-02-22 11:37:12.778  - error: zoe2.0 (30540) unhandled promise rejection: Cannot read property 'cookieValue' of undefined
2022-02-22 11:37:12.781  - error: zoe2.0 (30540) TypeError: Cannot read property 'cookieValue' of undefined
    at /opt/iobroker/node_modules/iobroker.zoe2/main.js:245:40
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
2022-02-22 11:37:12.782  - error: zoe2.0 (30540) Cannot read property 'cookieValue' of undefined
2022-02-22 11:37:12.791  - debug: zoe2.0 (30540) cleaned everything up...
2022-02-22 11:37:12.794  - info: zoe2.0 (30540) terminating
2022-02-22 11:37:12.796  - warn: zoe2.0 (30540) Terminated (UNCAUGHT_EXCEPTION): Without reason
pi@ioBroker-RasPi:~ $

**Comment by fungus75** [comment]
Danke, hier sieht man es genau:

2022-02-22 11:37:12.772 - info: zoe2.0 (30540) FullBody:{"callId":"0485247ba05f4de0b05c93eafd519bef","errorCode":403042,"errorDetails":"invalid loginID or password","errorMessage":"Invalid LoginID","apiVersion":2,"statusCode":403,"statusReason":"Forbidden","time":"2022-02-22T10:37:12.738Z"}

Bitte gib alle Parameter in der Adapter-Konfiguration neu ein. Da ist irgendwas nicht mehr richtig gespeichert.

**Comment by NoRitz952** [comment]
OK, danke Dir.Musste gerade außer Haus. Mache ich heute Nachmittag. --Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 22.02.22, 12:01 schrieb DerPilz ***@***.***>:

   
  Danke, hier sieht man es genau: 
  2022-02-22 11:37:12.772 - info: zoe2.0 (30540) FullBody:{"callId":"0485247ba05f4de0b05c93eafd519bef","errorCode":403042,"errorDetails":"invalid loginID or password","errorMessage":"Invalid LoginID","apiVersion":2,"statusCode":403,"statusReason":"Forbidden","time":"2022-02-22T10:37:12.738Z"} 
  Bitte gib alle Parameter in der Adapter-Konfiguration neu ein. Da ist irgendwas nicht mehr richtig gespeichert.

**Comment by NoRitz952** [comment]
So, alle Daten nochmal neu eingetragen, obwohl sie äußerlich noch da standen. Jetzt aber klappt's. 
Vielen Dank für Deine Hilfe!

**Comment by fungus75** [comment]
Hab für diesen Fall im Log eine sprechende Meldung eingebaut.
