### ISSUE TITLE
During connection always throws ERRORS

### ISSUE THREAD

**Issue by MichaelSchaaf999** [fungus75/ioBroker.zoe2#48]
Hi,
unfortunately the app throws errors while having successful connections to the server:

zoe2.0 | 2023-01-01 10:45:04.386 | error | Cannot read property 'status' of undefined
-- | -- | -- | --
zoe2.0 | 2023-01-01 10:45:04.386 | error | TypeError: Cannot read property 'status' of undefined at /opt/iobroker/node_modules/iobroker.zoe2/main.js:363:29 at processTicksAndRejections (internal/process/task_queues.js:95:5)
zoe2.0 | 2023-01-01 10:45:04.385 | error | unhandled promise rejection: Cannot read property 'status' of undefined
zoe2.0 | 2023-01-01 10:45:04.385 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zoe2.0 | 2023-01-01 10:45:04.385 | error | Error in step 5, errorCode: 2
zoe2.0 | 2023-01-01 10:45:04.384 | error | Error: timeout of 3000ms exceeded
zoe2.0 | 2023-01-01 10:45:04.384 | error | Maybe Kamereon-API Key has changed, please check https://github.com/fungus75/ioBroker.zoe2/wiki
zoe2.0 | 2023-01-01 10:45:04.383 | error | No valid response1 from getKamereonAccount service

The necessary values are being transferred correct, though.
What can we do to avoid these errors?
LG 
Michael

**Comment by fungus75** [comment]
Hi,

please upgrade to the very last version (use expert-mode in iobrokers-adapters, click on "from own URL" and enter that URL: https://github.com/fungus75/ioBroker.zoe2.git

After upgrading, please re-enter all parameters in setup-screen, also please enter the current API-Key from https://github.com/fungus75/ioBroker.zoe2/wiki

Hopefully it helps,

cu
 Fungus

**Comment by MichaelSchaaf999** [comment]
Update done, thanks, now:

![image](https://user-images.githubusercontent.com/53481090/210221948-1969005d-24ad-445c-88f6-cfebe98fba10.png)

It was not necessary to re-enter all the parameters: Everything was still present.

But:

zoe2.0 | 2023-01-02 11:30:06.253 | error | Cannot read property 'status' of undefined
-- | -- | -- | --
zoe2.0 | 2023-01-02 11:30:06.252 | error | TypeError: Cannot read property 'status' of undefined at /opt/iobroker/node_modules/iobroker.zoe2/main.js:580:29 at processTicksAndRejections (internal/process/task_queues.js:95:5)
zoe2.0 | 2023-01-02 11:30:06.252 | error | unhandled promise rejection: Cannot read property 'status' of undefined
zoe2.0 | 2023-01-02 11:30:06.252 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zoe2.0 | 2023-01-02 11:30:06.251 | error | Error in step 9, errorCode: 2
zoe2.0 | 2023-01-02 11:30:06.251 | error | Error: timeout of 3000ms exceeded
zoe2.0 | 2023-01-02 11:30:06.250 | error | No valid response1 from getLocation service

CU
M.

**Comment by Wiednitz** [comment]
Der Adapter läuft zur Zeit ohne Probleme. Aller paar Monate habe ich auch oben genannte Fehler und der Adapter stellt seine Arbeit ein, die Uhr neben dem Adapter ist dauerhaft blau, normal sollte die gelb sein. 
Drüber installieren bringt nix, Adapter komplett deinstallieren und neu installieren !

**Comment by MichaelSchaaf999** [comment]
--> "Drüber installieren bringt nix, Adapter komplett deinstallieren und neu installieren !"

This leads to some warnings:

"Befehl ausführen

Process exited with code 0
weniger

mehr
$ iobroker url https://github.com/fungus75/ioBroker.zoe2.git --host iobroker --debug
install fungus75/ioBroker.zoe2#759f83fcd615d1e3186185cc8f4ef8b0e8c61f0d
Installing fungus75/ioBroker.zoe2#759f83fcd615d1e3186185cc8f4ef8b0e8c61f0d... (System call)
npm WARN @material-ui/pickers@3.3.10 requires a peer of @material-ui/core@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @material-ui/pickers@3.3.10 requires a peer of react@^16.8.0 || ^17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN crc@4.1.1 requires a peer of buffer@>=6.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN react-transition-group@4.4.2 requires a peer of react@>=16.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-transition-group@4.4.2 requires a peer of react-dom@>=16.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN rifm@0.7.0 requires a peer of react@>=16.8 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):

added 3 packages from 5 contributors in 72.949s
221 packages are looking for funding run `npm fund` for details
upload [1] zoe2.admin /opt/iobroker/node_modules/iobroker.zoe2/admin/index_m.html index_m.html text/html
upload [0] zoe2.admin /opt/iobroker/node_modules/iobroker.zoe2/admin/zoe.png zoe.png image/png
Process exited with code 0"

and...  
![image](https://user-images.githubusercontent.com/53481090/210251168-5a53ea30-6efc-4688-ad52-e14992ce4b33.png)

But...
No Zoe-instance can be found. Sorry.

**Comment by fungus75** [comment]
> Update done, thanks, now:
> 
> ![image](https://user-images.githubusercontent.com/53481090/210221948-1969005d-24ad-445c-88f6-cfebe98fba10.png)
> 
> It was not necessary to re-enter all the parameters: Everything was still present.
> 
> But:
> 
> zoe2.0	2023-01-02 11:30:06.253	error	Cannot read property 'status' of undefined
> zoe2.0	2023-01-02 11:30:06.252	error	TypeError: Cannot read property 'status' of undefined at /opt/iobroker/node_modules/iobroker.zoe2/main.js:580:29 at processTicksAndRejections (internal/process/task_queues.js:95:5)
> zoe2.0	2023-01-02 11:30:06.252	error	unhandled promise rejection: Cannot read property 'status' of undefined
> zoe2.0	2023-01-02 11:30:06.252	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
> zoe2.0	2023-01-02 11:30:06.251	error	Error in step 9, errorCode: 2
> zoe2.0	2023-01-02 11:30:06.251	error	Error: timeout of 3000ms exceeded
> zoe2.0	2023-01-02 11:30:06.250	error	No valid response1 from getLocation service
> CU M.

Please try to adjust the timeout in setup-screen:
![image](https://user-images.githubusercontent.com/2380224/210424548-7ff41b16-ced6-480d-aeed-38c46128636f.png)

**Comment by fungus75** [comment]
> --> "Drüber installieren bringt nix, Adapter komplett deinstallieren und neu installieren !"
> 
> This leads to some warnings:
> 
> "Befehl ausführen
> 
> Process exited with code 0 weniger
> 
> mehr $ iobroker url https://github.com/fungus75/ioBroker.zoe2.git --host iobroker --debug install fungus75/ioBroker.zoe2#759f83fcd615d1e3186185cc8f4ef8b0e8c61f0d Installing fungus75/ioBroker.zoe2#759f83fcd615d1e3186185cc8f4ef8b0e8c61f0d... (System call) npm WARN @material-ui/pickers@3.3.10 requires a peer of @material-ui/core@^4.0.0 but none is installed. You must install peer dependencies yourself. npm WARN @material-ui/pickers@3.3.10 requires a peer of react@^16.8.0 || ^17.0.0 but none is installed. You must install peer dependencies yourself. npm WARN crc@4.1.1 requires a peer of buffer@>=6.0.3 but none is installed. You must install peer dependencies yourself. npm WARN react-transition-group@4.4.2 requires a peer of react@>=16.6.0 but none is installed. You must install peer dependencies yourself. npm WARN react-transition-group@4.4.2 requires a peer of react-dom@>=16.6.0 but none is installed. You must install peer dependencies yourself. npm WARN rifm@0.7.0 requires a peer of react@>=16.8 but none is installed. You must install peer dependencies yourself. npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
> 
> added 3 packages from 5 contributors in 72.949s 221 packages are looking for funding run `npm fund` for details upload [1] zoe2.admin /opt/iobroker/node_modules/iobroker.zoe2/admin/index_m.html index_m.html text/html upload [0] zoe2.admin /opt/iobroker/node_modules/iobroker.zoe2/admin/zoe.png zoe.png image/png Process exited with code 0"
> 
> and... ![image](https://user-images.githubusercontent.com/53481090/210251168-5a53ea30-6efc-4688-ad52-e14992ce4b33.png)
> 
> But... No Zoe-instance can be found. Sorry.

You can use the plus-sign in admin-screen to create an instance if not created automatically:

![image](https://user-images.githubusercontent.com/2380224/210424760-1f774e7a-319b-4d96-b730-2a4386f07347.png)

**Comment by fungus75** [comment]
It also works in the Tile-Display-Mode

![image](https://user-images.githubusercontent.com/2380224/210425032-071d71ba-4e0d-4129-99b7-7df5e1bea60b.png)

**Comment by MichaelSchaaf999** [comment]
yes, but this installs 02.5 NOT 02.6

**Comment by MichaelSchaaf999** [comment]
So: Repeated the installation process...
![image](https://user-images.githubusercontent.com/53481090/210497525-209d6f5e-9b3d-42fc-8933-c8a711959dda.png)
So it says 02.6 has been installed BUT still NO instance can be seen.
What do you recommend?

**Comment by MichaelSchaaf999** [comment]
Aktuell:
![image](https://user-images.githubusercontent.com/53481090/211321892-5da86618-92aa-4c2a-9d55-8376a565abb9.png)



Fehler:



host.iobroker | 2023-01-09 14:30:08.668 | error | instance system.adapter.zoe2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
zoe2.0 | 2023-01-09 14:30:08.163 | error | Cannot read property 'status' of undefined
zoe2.0 | 2023-01-09 14:30:08.163 | error | TypeError: Cannot read property 'status' of undefined at /opt/iobroker/node_modules/iobroker.zoe2/main.js:532:29 at processTicksAndRejections (internal/process/task_queues.js:95:5)
zoe2.0 | 2023-01-09 14:30:08.162 | error | unhandled promise rejection: Cannot read property 'status' of undefined
zoe2.0 | 2023-01-09 14:30:08.162 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zoe2.0 | 2023-01-09 14:30:08.162 | error | Error in step 8, errorCode: 2
zoe2.0 | 2023-01-09 14:30:08.161 | error | Error: timeout of 5000ms exceeded
zoe2.0 | 2023-01-09 14:30:08.161 | error | No valid response1 from getCockpit service

Was soll da nun noch geschehen?

LG 
M

**Comment by fungus75** [comment]
Kommt der Fehler regelmäßig vor, oder nur vereinzelt? Die API ist leider nicht stabil. z.B. um +/- 20:00 Uhr klappt es nicht,... Auch zwischendurch kommt es immer wieder zu Fehler. Aber 90% der Aufrufe sollten schon klappen.

Die im Screenhot angezeigten Fehler sind - so wie es sich für mich darstellt - nur Folgefehler des Timeouts.
Bei mir (allerdings Renault Twingo Electric) klappt es mit 5000 ms Timeout "recht gut", aber wie gesagt, vereinzelt kommt es zu obigen Fehler.

**Comment by MichaelSchaaf999** [comment]
Regelmässig.
Ich kann ja auch mal den TimeOut höher setzen, falls das was bringt. 50000 ms oder so?

**Comment by fungus75** [comment]
Hast du an dem Intervall vom Adapter geschraubt? Wird der Adapter nach wie vor alle 10 Minuten aufgerufen, oder öfter? Was wir mit einem anderen User schon herausgefunden haben: der Adapter läuft am stabilsten, wenn er allerhöchstens alle 3 Minuten aufgerufen wird. Darüber hinaus limitiert die API wohl.

**Comment by MichaelSchaaf999** [comment]
Nein, das Intervall ist unverändert:

<img width="1374" alt="image" src="https://user-images.githubusercontent.com/53481090/211329367-c062f65e-e000-4194-b086-4660de3d6677.png">

**Comment by MichaelSchaaf999** [comment]
Fehler liegt immer noch vor
